on:
  pull_request:
    paths-ignore:
    - '.github/workflows/**'
    - '*.md'
jobs:
  deploy-job:
    name: infracost
    uses: Liquid-Reply/shared-workflow/.github/workflows/infracost.yaml@main
    secrets:
      infracost_api_key: ${{ secrets.INFRACOST_API_KEY }}